my_list = [1, 2, 3]
print(type(my_list))
print(id(my_list))
my_list.append(4)
print(my_list)
print(id(my_list))
print("******************")
print()
my_list_1 = [1, 2, 3]
print(my_list_1)
print(id(my_list_1))
my_list_1 = my_list + [4]
print(my_list_1)
print(id(my_list_1))
print("******************")
print()
my_dict = dict(key1=1, key2='a')
print(my_dict)
print(id(my_dict))
my_dict['key3'] = 10.5
print(my_dict)
print(id(my_dict))
print("******************")
print()

t = (1, 2, 3)
print(id(t))
print(id(t[0]))
print(id(t[1]))
print(id(t[2]))
print()
t = ([1, 2], [3, 4])
print(id(t))
print(t[0])
print(id(t[0]))
print(t[1])
print(id(t[1]))
t[0].append(3)
print(t)
print(id(t))